### ISSUE TITLE
Switch N:2 suggestion

### ISSUE THREAD

**Issue by vcvrackideas** [23volts/23volts-vcv#22]
Hi Remi! This is pretty nice module, thanks! 
I have one suggestion about AUX triggers though. Could we extract triggers from this kind of connection? 
![2020-01-20_18-14-06](https://user-images.githubusercontent.com/42435368/72737727-2ab55b00-3bb1-11ea-9577-e1f5de733aca.png)
Triggers that following the red LED in the module. Would be cool feature because using CV input can easily prevent us from static gates\notes and this is cool for making arpeggiator indeed) I just like the behavior of your switch that triggering from CV input really.

**Comment by RemiCollin** [comment]
I have to test this, but I guess it should be possible.

**Comment by RemiCollin** [comment]
Ok it ended up being a little tricky, due to the dual/link nature of the module. I rewrote part of the code and split the TRIG output as well.

What becomes really interesting, is that with CV control and two signals with different number of channels, it can achieve truly polyrythmic sequences.

**Comment by vcvrackideas** [comment]
> Ok it ended up being a little tricky, due to the dual/link nature of the module. I rewrote part of the code and split the TRIG output as well.
> 
> What becomes really interesting, is that with CV control and two signals with different number of channels, it can achieve truly polyrythmic sequences.

thanks! just have tested it - pretty cool! it's like a comparator part of Rampage for poly inputs, masterpiece, future classic!)
a little suggestion - A B trigger\gate switch in right click menu, is it possible? just for making sequences even faster) or it's hard to determine a gate length? oops, just noticed that you're panel already contains word "trig" so it's really up to you Remi.

**Comment by RemiCollin** [comment]
> a little suggestion - A B trigger\gate switch in right click menu, is it possible? just for making sequences even faster) or it's hard to determine a gate length? oops, just noticed that you're panel already contains word "trig" so it's really up to you Remi.

I plan to add gates yes. Triggers was just faster to implement to test the concept out.

**Comment by vcvrackideas** [comment]
> Triggers was just faster to implement to test the concept out.

and this realization of the concept is excellent. thanks again!

**Comment by RemiCollin** [comment]
Ok, I renamed `CV` to `Phase` as it's more meaningful. Now it outputs Gate when the Phase input is "synced", but will output triggers if it's control with a non linear signal.

**Comment by vcvrackideas** [comment]
> Ok, I renamed `CV` to `Phase` as it's more meaningful. Now it outputs Gate when the Phase input is "synced", but will output triggers if it's control with a non linear signal.

Thanks! Great addition to ZZC phased stuff! However noticed that nonlinear inputs such as sine wave get the gate stuck on 10 volts
![2020-01-22_15-21-55](https://user-images.githubusercontent.com/42435368/72893875-27de7580-3d2b-11ea-92ac-735a575007d5.png)
Also noticed that if Square wave connected into Phase - it doesn't use the last note in the sequence when 10v, just reduced it a bit and the last note switching is ok now.
EDIT: and another one - probability CV output works only when triggers\gates connected to step +\- and RND, is that ok?

**Comment by RemiCollin** [comment]
I couldn't reproduce the stuck 10v gate. 

Fixed other issues ;)

**Comment by vcvrackideas** [comment]
> I couldn't reproduce the stuck 10v gate.

![stuck phase sine](https://user-images.githubusercontent.com/42435368/72895691-01223e00-3d2f-11ea-9aa2-858c5aca6cd9.gif)
Just connect sine to the phase and got it. Strange, red LED is still switching poly input

**Comment by RemiCollin** [comment]
That's exactly what I did. Are you using last version of the code ?

**Comment by vcvrackideas** [comment]
> That's exactly what I did. Are you using last version of the code ?

just pull it again from dev branch - same result( it bring 1 gate and then on the second gate it stuck on 10 volts. strange

**Comment by RemiCollin** [comment]
Can you please send me your patch file ? (23volts@gmail.com)

**Comment by vcvrackideas** [comment]
> Can you please send me your patch file ? ([23volts@gmail.com](mailto:23volts@gmail.com))

Done)

**Comment by RemiCollin** [comment]
Ok thank you. Really weird, I don't have this happening on my side.. Still happen if you start a new patch from scratch with new version ?

**Comment by vcvrackideas** [comment]
> Ok thank you. Really weird, I don't have this happening on my side.. Still happen if you start a new patch from scratch with new version ?

just tried to remove everything, then restart rack to make another try - but it's still the same(

**Comment by RemiCollin** [comment]
Ok I'll see about that later on, as I still found some issue with the new implementation when using shapes other than saw
